#!/bin/bash
#2425..2430

for ((i = $1; i <= $2; i++)); do
	a1=0;a2=0;a3=0;a4=0;a5=0;a6=0;a7=0;a8=0;a9=0
	echo "a.n1,b.n2,c.n3,d.n4,f.n5,g.n6,h.n7,i.n8,amt.n9,$i=>tot" >> ~/scripts/sqspreads/$i.csv
	eg=$(( i*i ))
	amt=$(( eg/5 ))
	rem=$(( eg%5 ))
	let "ln=9*$amt+$rem"
	len=${#ln}
	let "spc=$len+1"
	printf "\n\nSquare: $eg ($i)"
	printf "\n\e[32ma%"$len"s b%"$len"s c%"$len"s d%"$len"s f%"$len"s g%"$len"s h%"$len"s i\e[0m\n\n"
		while [ "$amt" -ne 0 ]; do
			sq=0
			prg=$(bc <<< "scale=3;$amt/($eg/5)")
			prg=$(bc <<< "scale=2;($prg+0.005)/1")
			prg=$(bc <<< "100*(1-$prg)")
			prg=${prg%.*}

			let "a=2*$amt+$rem"
			al=${#a}
			let "al=$len-$al+2"

			let "b=7*$amt+$rem"
			bl=${#b}
			let "bl=$len-$bl+2"		
			
			let "c=6*$amt+$rem"
			cl=${#c}
			let "cl=$len-$cl+2"		
			
			let "d=9*$amt+$rem"
			dl=${#d}
			let "dl=$len-$dl+2"		
			
			let "f=1*$amt+$rem"
			fl=${#f}
			let "fl=$len-$fl+2"		
			
			let "g=4*$amt+$rem"
			gl=${#g}
			let "gl=$len-$gl+2"		
			
			let "h=3*$amt+$rem"
			hl=${#h}
			let "hl=$len-$hl+2"		
			
			let "j=8*$amt+$rem"
			jl=${#j}
			let "jl=$len-$jl+2"		
			
			if grep -Fxq "$a" ~/scripts/squares.txt ; then
				a="x$a"
				(( al-- ))
				out="\e[31m$a\e[0m%"$al"s"
				let "sq++"
			else
				out="$a%"$al"s"
			fi

			if grep -Fxq "$b" ~/scripts/squares.txt ; then
				b="x$b"
				(( cl-- ))
				out="$out\e[31m$b\e[0m%"$bl"s"
				let "sq++"
			else
				out="$out$b%"$bl"s"
			fi

			if grep -Fxq "$c" ~/scripts/squares.txt ; then
				c="x$c"
				(( cl-- ))
				out="$out\e[31m$c\e[0m%"$cl"s"
				let "sq++"
			else
				out="$out$c%"$cl"s"
			fi

			if grep -Fxq "$d" ~/scripts/squares.txt ; then
				d="x$d"
				(( dl-- ))
				out="$out\e[31m$d\e[0m%"$dl"s"
				let "sq++"
			else
				out="$out$d%"$dl"s"
			fi

			if grep -Fxq "$f" ~/scripts/squares.txt ; then
				f="x$f"
				(( fl-- ))
				out="$out\e[31m$f\e[0m%"$fl"s"
				let "sq++"
			else
				out="$out$f%"$fl"s"
			fi

			if grep -Fxq "$g" ~/scripts/squares.txt ; then
				g="x$g"
				(( gl-- ))
				out="$out\e[31m$g\e[0m%"$gl"s"
				let "sq++"
			else
				out="$out$g%"$gl"s"
			fi

			if grep -Fxq "$h" ~/scripts/squares.txt ; then
				h="x$h"
				(( hl-- ))
				out="$out\e[31m$h\e[0m%"$hl"s"
				let "sq++"
			else
				out="$out$h%"$hl"s"
			fi

			if grep -Fxq "$j" ~/scripts/squares.txt ; then
				j="x$j"
				(( jl-- ))
				out="$out\e[31m$j\e[0m%"$jl"s"
				let "sq++"
			else
				out="$out$j%"$jl"s"
			fi
			
			if [ "$sq" -ne 0 ]; then
				tsq=$(( tsq+sq ))
				(( a$sq++ ))
				printf "\033[1A"
				printf "\033[K"
				printf "$out\e[3"$sq"m%3s$sq\e[0m%3s$amt\n"
				printf "\033[K"
				printf "\e[32ma%"$len"s b%"$len"s c%"$len"s d%"$len"s f%"$len"s g%"$len"s h%"$len"s i\e[0m\n"
				printf "Progress: $prg%% done.  $tsq\r"
				echo "$a,$b,$c,$d,$f,$g,$h,$j,$amt,$sq" >> ~/scripts/sqspreads/$i.csv

			else
				printf "Progress: $prg%% done.  $tsq\r"
			fi

			if [ "$sq" -eq 4 ]; then
				printf "\n"
				exit 1
			fi

			amt=$(( amt-1 ))
			rem=$(( rem+5 ))
		done
	sed -i "s/tot/$tsq/g" ~/scripts/sqspreads/$i.csv
	for p in {1..9}; do	
		temp="a$p"
		sed -i "s/n$p/${!temp}/g" ~/scripts/sqspreads/$i.csv
	done
		unset tsq
done
