#!/bin/bash

for i in {2424..2430}
do
	eg=$(( i*i ))
	amt=$(( eg/5 ))
	rem=$(( eg%5 ))
	let "ln=9*$amt+$rem"
	len=${#ln}
	let "spc=$len+1"
	printf "\n\nSquare: $eg ($i)"
	printf "\n\e[32ma%"$len"s b%"$len"s c%"$len"s d%"$len"s f%"$len"s g%"$len"s h%"$len"s i\e[0m"
		while [ "$amt" -ne 0 ]
		do
			sq=0

			let "a=2*$amt+$rem"
			al=${#a}
			let "al=$len-$al+2"

			let "b=7*$amt+$rem"
			bl=${#b}
			let "bl=$len-$bl+2"		
			
			let "c=6*$amt+$rem"
			cl=${#c}
			let "cl=$len-$cl+2"		
			
			let "d=9*$amt+$rem"
			dl=${#d}
			let "dl=$len-$dl+2"		
			
			let "f=1*$amt+$rem"
			fl=${#f}
			let "fl=$len-$fl+2"		
			
			let "g=4*$amt+$rem"
			gl=${#g}
			let "gl=$len-$gl+2"		
			
			let "h=3*$amt+$rem"
			hl=${#h}
			let "hl=$len-$hl+2"		
			
			let "j=8*$amt+$rem"
			jl=${#j}
			let "jl=$len-$jl+2"		
			
			amt=$(( amt-1 ))
			rem=$(( rem+5 ))

			if grep -Fxq "$a" squares.txt ; then
				printf "\n\e[31m$a\e[0m%"$al"s"
				let "sq++"
			else
				printf "\n$a%"$al"s"
			fi

			if grep -Fxq "$b" squares.txt ; then
				printf "\e[31m$b\e[0m%"$bl"s"
				let "sq++"
			else
				printf "$b%"$bl"s"
			fi

			if grep -Fxq "$c" squares.txt ; then
				printf "\e[31m$c\e[0m%"$cl"s"
				let "sq++"
			else
				printf "$c%"$cl"s"
			fi

			if grep -Fxq "$d" squares.txt ; then
				printf "\e[31m$d\e[0m%"$dl"s"
				let "sq++"
			else
				printf "$d%"$dl"s"
			fi

			if grep -Fxq "$f" squares.txt ; then
				printf "\e[31m$f\e[0m%"$fl"s"
				let "sq++"
			else
				printf "$f%"$fl"s"
			fi

			if grep -Fxq "$g" squares.txt ; then
				printf "\e[31m$g\e[0m%"$gl"s"
				let "sq++"
			else
				printf "$g%"$gl"s"
			fi

			if grep -Fxq "$h" squares.txt ; then
				printf "\e[31m$h\e[0m%"$hl"s"
				let "sq++"
			else
				printf "$h%"$hl"s"
			fi

			if grep -Fxq "$j" squares.txt ; then
				printf "\e[31m$j\e[0m%"$jl"s"
				let "sq++"
			else
				printf "$j%"$jl"s"
			fi

			printf "\e[3"$sq"m%3s$sq\e[0m%3s$amt"

			if [ "$sq" -eq 4 ]; then
				printf "\n"
				exit 1
			fi
		done
done
printf "\n"
